#!/bin/bash

if [ $( date +"%H" ) -gt 6 ]
then
	# Over 6am, check from today's 6am
	git log --numstat --oneline --since="$( date --date="6:00" )" | \
	gawk '{printf "%s\t%s\n", $1, $2}' | \
	gawk 'BEGIN{nAdd=0; nSub=0;} {match($0, /([0-9]+)\t([0-9]+)/, m); nAdd+=m[1]; nSub+=m[2]} END{print nAdd, nSub}'
else
	# Not yet 6am, check from yesterday's 6am
	git log --numstat --oneline --since="$( date --date="yesterday 6:00" )" | \
	gawk '{printf "%s\t%s\n", $1, $2}' | \
	gawk 'BEGIN{nAdd=0; nSub=0;} {match($0, /([0-9]+)\t([0-9]+)/, m); nAdd+=m[1]; nSub+=m[2]} END{print nAdd, nSub}'
fi